const mongoose = require('mongoose');

const accountSchema = new mongoose.Schema({
  robloxId: { type: String, required: false, default: null },
  username: { type: String, required: false, default: null },
  displayName: { type: String, required: false, default: null },
  description: { type: String, required: false, default: null },
  thumbnail: { type: String, required: false, default: null },
  rank: { type: String, required: false, default: "USER" },
  level: { type: Number, required: false, default: 0 },
  deposited: { type: Number, required: false, default: 0 },
  withdrawn: { type: Number, required: false, default: 0 },
  wagered: { type: Number, required: false, default: 0 },
  totalBets: { type: Number, required: false, default: 0 },
  gameWins: { type: Number, required: false, default: 0 },
  diceClientSeed: String,
  limboClientSeed: String,
  minesClientSeed: String,
  blackjackClientSeed: String,
  diceServerSeed: String,
  limboServerSeed: String,
  minesServerSeed: String,
  blackjackServerSeed: String,
  diceNonce: { type: Number, default: 0 },
  limboNonce: { type: Number, default: 0 },
  minesNonce: { type: Number, default: 0 },
  blackjackNonce: { type: Number, default: 0 },
  diceHistory: { type: Array, default: [] },
  limboHistory: { type: Array, default: [] }, 
  minesHistory: { type: Array, default: [] }, 
  blackjackHistory: { type: Array, default: [] }, 
  BTCAddress: { type: String },
  ETHAddress: { type: String },
  LTCAddress: { type: String },
  BNBAddress: { type: String },
  USDTAddress: { type: String },
  withdrawalWalletAddresses: { type: Array, default: [] },
  ips: { type: Array, default: [] },
  balance: { type: Number, required: false, default: 0 },
  joinDate: { type: Date, required: false, default: new Date() },
  lastMessage: { type: Date, required: false, default: new Date() },
  referrer: {},
  affiliate: {
    wagered: { type: Number },
    totalEarnings: { type: Number },
    balance: { type: Number },
    referrals: { type: Array, default: [] },
  },
});

module.exports = mongoose.model('Account', accountSchema);
